### ISSUE TITLE
Type xsd:integer not implemented

### ISSUE THREAD

**Issue by ooxi** [GoComply/xsd2go#3]
I'm running into an issue when trying to generate a binding for a fairly simple XSD. Should `xsd:int` or `xsd:integer` be supported by now?

# XSD

```
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema	xmlns:xsd="http://www.w3.org/2001/XMLSchema"

		xmlns:simple-schema="https://simple.example.com/"
		targetNamespace="https://simple.example.com/"
		elementFormDefault="qualified">

	<xsd:element name="myelement" type="simple-schema:MyElementType" />

	<xsd:complexType name="MyElementType">
		<xsd:sequence>
			<xsd:element name="id" type="xsd:integer" />
		</xsd:sequence>
	</xsd:complexType>


</xsd:schema>
```

# Output

```
/home/pi/go/bin/gocomply_xsd2go convert simple.xsd simple.example.com/1.0 go
Processing 'simple.xsd'
	Parsing: simple.xsd
panic: Type xsd:integer not implemented

goroutine 1 [running]:
github.com/gocomply/xsd2go/pkg/xsd.StaticType(...)
	/home/pi/go/src/github.com/gocomply/xsd2go/pkg/xsd/types.go:192
github.com/gocomply/xsd2go/pkg/xsd.(*Schema).findReferencedType(0x1d42380, 0x1ec3270, 0xb, 0x659c0458, 0x4f2520)
	/home/pi/go/src/github.com/gocomply/xsd2go/pkg/xsd/schema.go:87 +0x5bc
github.com/gocomply/xsd2go/pkg/xsd.(*Element).compile(0x1d3cfc0, 0x1d42380, 0x0)
	/home/pi/go/src/github.com/gocomply/xsd2go/pkg/xsd/element.go:134 +0x1c8
github.com/gocomply/xsd2go/pkg/xsd.(*Sequence).compile(0x1ee0d80, 0x1d42380, 0x0)
	/home/pi/go/src/github.com/gocomply/xsd2go/pkg/xsd/sequence.go:21 +0x48
github.com/gocomply/xsd2go/pkg/xsd.(*ComplexType).compile(0x1d2e7d0, 0x1d42380, 0x0)
	/home/pi/go/src/github.com/gocomply/xsd2go/pkg/xsd/types.go:73 +0x320
github.com/gocomply/xsd2go/pkg/xsd.(*Schema).compile(0x1d42380)
	/home/pi/go/src/github.com/gocomply/xsd2go/pkg/xsd/schema.go:54 +0xa8
github.com/gocomply/xsd2go/pkg/xsd.(*Workspace).loadXsd(0x1d1caf0, 0x7ea61e33, 0xa, 0x0, 0x0, 0x0)
	/home/pi/go/src/github.com/gocomply/xsd2go/pkg/xsd/workspace.go:51 +0x2c0
github.com/gocomply/xsd2go/pkg/xsd.NewWorkspace(0x1ede0a0, 0x19, 0x7ea61e33, 0xa, 0x2, 0x1ede0a0, 0x19)
	/home/pi/go/src/github.com/gocomply/xsd2go/pkg/xsd/workspace.go:20 +0x6c
github.com/gocomply/xsd2go/pkg/xsd2go.Convert(0x7ea61e33, 0xa, 0x7ea61e3e, 0x16, 0x7ea61e55, 0x2, 0x0, 0x0)
	/home/pi/go/src/github.com/gocomply/xsd2go/pkg/xsd2go/generate.go:12 +0x120
github.com/gocomply/xsd2go/cli/cmd.glob..func2(0x1d62840, 0x1d11000, 0x0)
	/home/pi/go/src/github.com/gocomply/xsd2go/cli/cmd/cmd.go:33 +0x64
github.com/gocomply/xsd2go/vendor/github.com/urfave/cli.HandleAction(0x2a00e0, 0x32a604, 0x1d62840, 0x1d62840, 0x0)
	/home/pi/go/src/github.com/gocomply/xsd2go/vendor/github.com/urfave/cli/app.go:526 +0xe4
github.com/gocomply/xsd2go/vendor/github.com/urfave/cli.Command.Run(0x2e3eac, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2f64c7, 0x44, 0x0, ...)
	/home/pi/go/src/github.com/gocomply/xsd2go/vendor/github.com/urfave/cli/command.go:174 +0x3f8
github.com/gocomply/xsd2go/vendor/github.com/urfave/cli.(*App).Run(0x1d04c40, 0x1d2c000, 0x5, 0x6, 0x0, 0x0)
	/home/pi/go/src/github.com/gocomply/xsd2go/vendor/github.com/urfave/cli/app.go:279 +0x54c
github.com/gocomply/xsd2go/cli/cmd.Execute(0x0, 0x1c000e0)
	/home/pi/go/src/github.com/gocomply/xsd2go/cli/cmd/cmd.go:18 +0xdc
main.main()
	/home/pi/go/src/github.com/gocomply/xsd2go/cli/gocomply_xsd2go/main.go:8 +0x14
Makefile:12: recipe for target 'generate' failed
make: *** [generate] Error 2
```

**Comment by isimluk** [comment]
Fixed. Thank You for the report!
