### ISSUE TITLE
panic: Type xsd:time not implemented

### ISSUE THREAD

**Issue by adamdecaf** [GoComply/xsd2go#63]
When parsing `pacs.008.001.09.xsd` from the [ISO 20022 standards](https://www.iso20022.org/iso-20022-message-definitions). (`FIToFICustomerCreditTransferV10`)

```
goroutine 1 [running]:
github.com/gocomply/xsd2go/pkg/xsd.StaticType(...)
	/Users/adam/code/pkg/mod/github.com/gocomply/xsd2go@v0.1.4/pkg/xsd/types.go:259
github.com/gocomply/xsd2go/pkg/xsd.(*Schema).findReferencedType(0xc0001bcc80, {0xc0002cb3d0, 0x7})
	/Users/adam/code/pkg/mod/github.com/gocomply/xsd2go@v0.1.4/pkg/xsd/schema.go:94 +0x2f9
github.com/gocomply/xsd2go/pkg/xsd.(*Restriction).compile(0xc0001fbb00, 0xc0001bcc80, 0x118637e?)
	/Users/adam/code/pkg/mod/github.com/gocomply/xsd2go@v0.1.4/pkg/xsd/restriction.go:31 +0xe5
github.com/gocomply/xsd2go/pkg/xsd.(*SimpleType).compile(...)
	/Users/adam/code/pkg/mod/github.com/gocomply/xsd2go@v0.1.4/pkg/xsd/types.go:179
github.com/gocomply/xsd2go/pkg/xsd.(*Schema).compile(0xc0001bcc80)
	/Users/adam/code/pkg/mod/github.com/gocomply/xsd2go@v0.1.4/pkg/xsd/schema.go:65 +0x1b7
github.com/gocomply/xsd2go/pkg/xsd.(*Workspace).loadXsd(0xc0001b25a0, {0x7ff7bfeff490, 0x19}, 0x1)
	/Users/adam/code/pkg/mod/github.com/gocomply/xsd2go@v0.1.4/pkg/xsd/workspace.go:86 +0xda9
github.com/gocomply/xsd2go/pkg/xsd.NewWorkspace({0xc0001b87c0, 0x1d}, {0x7ff7bfeff490, 0x19}, {0x15ce3c0, 0x0, 0x0})
	/Users/adam/code/pkg/mod/github.com/gocomply/xsd2go@v0.1.4/pkg/xsd/workspace.go:27 +0xfc
github.com/gocomply/xsd2go/pkg/xsd2go.Convert({0x7ff7bfeff490, 0x19}, {0x7ff7bfeff4aa, 0x1a}, {0x7ff7bfeff4c5, 0x2}, {0x15ce3c0, 0x0, 0x0})
	/Users/adam/code/pkg/mod/github.com/gocomply/xsd2go@v0.1.4/pkg/xsd2go/generate.go:12 +0x15a
github.com/gocomply/xsd2go/cli/cmd.glob..func2(0xc0001c8dc0?)
	/Users/adam/code/pkg/mod/github.com/gocomply/xsd2go@v0.1.4/cli/cmd/cmd.go:44 +0xd1
github.com/urfave/cli.HandleAction({0x12d1740?, 0x135f420?}, 0x7?)
	/Users/adam/code/pkg/mod/github.com/urfave/cli@v1.22.10/app.go:524 +0x50
github.com/urfave/cli.Command.Run({{0x132b381, 0x7}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x134176d, 0x44}, {0x0, ...}, ...}, ...)
	/Users/adam/code/pkg/mod/github.com/urfave/cli@v1.22.10/command.go:173 +0x65b
github.com/urfave/cli.(*App).Run(0xc0001c0700, {0xc0000160a0, 0x5, 0x5})
	/Users/adam/code/pkg/mod/github.com/urfave/cli@v1.22.10/app.go:277 +0x8c7
github.com/gocomply/xsd2go/cli/cmd.Execute()
	/Users/adam/code/pkg/mod/github.com/gocomply/xsd2go@v0.1.4/cli/cmd/cmd.go:21 +0x134
main.main()
	/Users/adam/code/pkg/mod/github.com/gocomply/xsd2go@v0.1.4/cli/gocomply_xsd2go/main.go:8 +0x19
```

**Comment by pervrosen** [comment]
W3C XML Schema Definition Language (XSD) 1.1 Part 2: Datatypes
https://www.w3.org/TR/2012/REC-xmlschema11-2-20120405/datatypes.html#dt-dt-7PropMod

According to w3c one could include time, gYear, gMonth etc... in pkg/xsd/types.go in the struct below (row 246->r 27x)
```
var staticTypes = map[string]staticType{
        "string":             "string",
        "dateTime":           "string",
        "date":               "string",
        "base64Binary":       "string",
        "normalizedString":   "string",
        "token":              "string",
        "NCName":             "string",
        "NMTOKENS":           "string",
        "anySimpleType":      "string",
        "anyType":            "string",
        "int":                "int",
        "integer":            "int64", 
        "long":               "int64",
        "nonNegativeInteger": "int",
        "anyURI":             "string",
        "double":             "float64",
        "decimal":            "float64", // no: http://books.xmlschemata.org/relaxng/ch19-77057.html
        "float":              "float64",
        "boolean":            "bool",
        "ID":                 "string",
        "positiveInteger":    "uint64",
        "unsignedInt":        "uint64",
        "gYear":              "string",
        "gYearMonth":         "string",
        "gMonthDay":          "string", 
        "gDay":               "string",
        "gMonth":             "string",
        "time":               "string",
} 
```
It will compile, but then we do not have any syntax checking (as prescribed by w3c). (Started playing with this package and the iso20022 xsds myself today and extended types.go like mentioned above. Have not used the results yet, but I tried pain001, pacs008, camt052, camt053 and camt054 with non-failing code) Hope it helps.

**Comment by adamdecaf** [comment]
Are you saying there's an option here to add more values to that staticTypes map? I was able to [generate code for ISO20022 xsds](https://github.com/moov-io/rtp20022) with another project, but would help here if it's straightforward.

**Comment by pervrosen** [comment]
I can at least create models from pain, camt and pacs now. Try it out and look out for side-effects.

**Comment by isimluk** [comment]
@adamdecaf, @pervrosen, thank you for your patience on this.

I think it is worth adding these types as strings. Even though it is not ideal, it is better than not having them. So, in my mind this is small improvement.

If you would like to implement custom types that would parse time/date properly, I would be more than happy to review your PRs.
